---
excludes:
  - Stage
  - Class
  - Anchor
  - Notify
  - Node
  - /::/
only_include: []
md5sums: false
class_name: null
catalog_file: null
output_file: spec/classes/init_spec.rb
compile_test: true
setup: {}
