---
# Resource types to exclude, i.e. to not write out as Rspec expectations. The
# /::/ excludes all defined types.
#
:excludes:
  - Stage
  - Class
  - Anchor
  - Notify
  - Node
  - /::/

# only_include and excludes are mutually exclusive, and only_include takes
# precedence. A list of specific resources specified as [Type[title],...], to
# be read as "only include [Type1[title2],Type2[title2]...].
#
:only_include: []

# Use full file content rather than MD5 sum checks of the content in the
# generated tests.
#
:md5sums: false

# Class name to declare. By default is auto-detected.
:class_name: null

# Default setup.
:setup: {}
